Bug 1924830: CVE-2021-3121 gogo/protobuf lacks certain index validation
openshift/sdn pull request #265
Opened 2021-03-04 01:35 UTC by abhat

This commit udpates the protobuf version used in sdn to 1.3.2
to address the CVE-2021-3121

Signed-off-by: Aniket Bhat <anbhat@redhat.com>

Backport of #260.

2021-03-04 01:35 UTC, abhat commented
/assign @vpickard

2021-03-08 13:10 UTC, vpickard requested changes
@abhat Take a look at this comment from @fedepaol on a similiar PR for ovn-kubernetes.

https://github.com/ovn-org/ovn-kubernetes/pull/2006#issuecomment-773142959

tl;dr; you need to add this in the replace section:
github.com/gogo/protobuf => github.com/gogo/protobuf v1.3.2

2021-03-09 17:38 UTC, abhat commented
@vpickard PTAL.

2021-03-16 12:53 UTC, vpickard reviewed
LGTM

2021-03-22 17:55 UTC, abhat commented
/bugzilla refresh

2021-03-22 20:23 UTC, abhat commented
/test e2e-aws-upgrade
/test e2e-gcp

2021-03-22 20:37 UTC, vpickard commented
/lgtm

2021-03-25 02:43 UTC, merged

2021-04-15 23:10 UTC, abhat commented
/bugzilla refresh